project: enzyme-stability

loss:
  ddG_lambda: 0.5
  dTm_lambda: 0.5
  seq_lambda: 0.5

learn_rate: 0.01

model:
  type: transfer
  hidden_dims: [50, 20]
  subtract_mut: true
  num_final_layers: 2
  use_msa: true
  freeze_weights: false

data:
  max_protein_length: 500
  num_pdb_datapoints: 1000

platform:
  cache_dir: "/home/boris/Data/enzyme_stability_cache"
  pdb_dir: "/home/boris/Data/pdb_2021aug02"