project: enzyme-stability
name: test_run

loss:
  ddG_lambda: 0.5
  dTm_lambda: 0.5
  seq_lambda: 0.0

learn_rate: 0.01

model:
  type: transfer
  hidden_dims: [16, 16, 8, 8]
  subtract_mut: true
  num_final_layers: 2
  use_msa: false
  freeze_weights: true

data:
  max_protein_length: 500
  num_pdb_datapoints: 1000