project: enzyme-stability
name: test_run

datasets: [rocklin]

loss:
  ddG_lambda: 1.0
  dTm_lambda: 0.0
  seq_lambda: 0.0

learn_rate: 0.01

model:
  type: transfer
  hidden_dims: [64, 32]
  subtract_mut: true
  num_final_layers: 2
  use_msa: false
  freeze_weights: false

data:
  max_protein_length: 500
  num_pdb_datapoints: 1000